# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readonly', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('down', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'mode',
                'verbose_name': 'mode',
                'verbose_name_plural': 'mode',
            },
        ),
    ]
