# Generated by Django 4.2.2 on 2023-09-07 20:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readonly', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('down', models.BooleanField(default=False)),
            ],
            options={'verbose_name': 'mode', 'verbose_name_plural': 'mode', 'db_table': 'mode', 'ordering': ('id',)},
        )
    ]
