# Generated by Django 4.2.2 on 2023-09-07 20:52

import versatileimagefield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('gstin', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('account_name', models.CharField(max_length=128)),
                ('account_number', models.CharField(max_length=128)),
                ('ifsc', models.CharField(max_length=128)),
                ('sales_person', models.CharField(max_length=128)),
                ('job', models.CharField(max_length=128)),
                ('shipping_method', models.CharField(default='', max_length=128)),
                ('shipping_terms', models.CharField(default='', max_length=128)),
                ('payment_terms', models.CharField(default='', max_length=128)),
                (
                    'logo',
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to='shop/', verbose_name='Logo'
                    ),
                ),
            ],
            options={'ordering': ('name',)},
        )
    ]
