# Generated by Django 4.2.2 on 2023-09-07 20:52

import uuid

import django.db.models.deletion
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                (
                    'photo',
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to='customers/', verbose_name='Photo'
                    ),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='creator_%(class)s_objects',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'updater',
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='updator_%(class)s_objects',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'ordering': ('-date_added', 'name')},
        )
    ]
